[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "openai_afc"
version = "0.0.1"
authors = [{ name="Anders Lie", email="anders.erik.lie@gmail.com" }]
dependencies = ["openai"]
